DESKTOP VERSION REVIEW REQUEST
pmaxy/Portfolio-finish-mobile-version pull request #4
Opened 2022-12-08 11:52 UTC by pmaxy

Things i did:

> Add new CSS file.
> Use media query.
> Add styles

2022-12-08 13:03 UTC, Felix45 requested changes
Hi @pmaxy , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights :heavy_check_mark: 
- [ ] All the linter checks are setup and passing with green checks :white_check_mark: 
- [ ] GitHub flow is used correctly :white_check_mark: 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 13:03 UTC, Felix45 commented on style.css
> +  height: 5500px;
- [ Required ] Please note that for mobile devices with a width greater than `375px` the width of the content on the webpage is not responsive. Your design maintains a width of `375px` even when the device has a width greater than `375px`. It's good practice to not apply fixed widths to elements on your page in order to make the webpage responsive, for example, to make the mobile navigation menu responsive across all mobile devices i would recommend the following `CSS` rules.

```CSS
body {
  font-family: 'Poppins', sans-serif;
  align-items: center;
  margin: auto;
  background: #f7f7f9;
  position: relative;
  height: 5500px;
}

header {
  left: 0;
  top: 0;
  right: 0;
  height: 92px;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  position: sticky;
  z-index: 2;
  background-color: #fff;
  margin: 0;
}
```
Removing the fixed width on the `body` and `header` elements makes the navigation menu adapt to mobile screen sizes with widths greater than `375px`
- Please consider dropping all the fixed widths on different sections of your design for mobile devices, please see the screenshot below for more details on this. The margins on the design at a width of `576px` should not be this large.

![Screenshot from 2022-12-08 15-37-25](https://user-images.githubusercontent.com/16392046/206452611-72ffde31-0079-49fe-a296-49479a2f66b2.png)

2022-12-09 00:46 UTC, franclobo approved these changes
Hi @pmaxy, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Descriptive PR ✔️ 
- Professional README file ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 00:46 UTC, franclobo commented on desktop.css
> +  }
- [ ] **[OPTIONAL]** On the desktop version there are two lines in the Figma version but in yours, there are three, please 🙏🏽 correct it to be similar to the Figma version.

| Figma version | Your version |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/206596880-e99ee51d-21ad-4e3f-95c0-d09e1fb9d648.png) | ![image](https://user-images.githubusercontent.com/58642949/206596830-9ea34c25-6f3d-4c14-8065-57672a0f0aae.png) |

2022-12-09 19:49 UTC, merged